import { createContext } from "react";

const ContextStore = createContext({
  handleLoginState: () => {},
  activeUser: ``,
  setActiveUser: () => {},
  handleSignupState: ``,
  acessDetail: ``,
  defaultCatogery: ``,
  loggedIn: ``,
  setLoggedIn: () => {},
  modalStatus: ``,
  setModalStatus: () => {},
  userCatogery: ``,
  setUserCatogery: () => {},
  incomeData: ``,
  setIncomeData: () => {},
  ExpenceData: ``,
  setExpenceData: () => {},
  setUserInput: () => {},
  UserInput: ``,
  setRefreshData: () => {},
  setAddCatogery: () => {},
  activeMonth: ``,
  setActiveMonth: () => {},
  filteredExpence: ``,
  filteredIncome: ``,
  checkCat: ``,
  setCheckCat: () => {},
  errors: ``,
  setErrors: () => {},
  refresdData: ``,
  handleLoginState: () => {},
  ConfimLogin: () => {},
  onChangeLogin: () => {},
  errors: ``,
  signUpOnchange: () => {},
  ConfirmSignup: () => {},
  handelpass: () => {},
  handleOLdPAss: () => {},
  ValidPass: () => {},
  totalIncome: ``,
  setTotalIncome: () => {},
  totalExpense: ``,
  setTotaExpense: () => {},
});

export default ContextStore;
